version: 2.1
jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/circle-ci:stitch-tap-tester-uv
    steps:
      - checkout
      - run:
          name: 'Setup virtual env'
          command: |
            uv venv --python 3.12 /usr/local/share/virtualenvs/tap-harvest
            source /usr/local/share/virtualenvs/tap-harvest/bin/activate
            uv pip install .
            uv pip install pylint
      - run:
          name: 'JSON Validator'
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            stitch-validate-json tap_harvest/schemas/*.json
      - run:
          name: 'pylint'
          command: |
            source /usr/local/share/virtualenvs/tap-harvest/bin/activate
            uv pip install pylint
            pylint tap_harvest -d C,R,W
      - add_ssh_keys
      - run:
          name: 'Unit Tests'
          command: |
            source /usr/local/share/virtualenvs/tap-harvest/bin/activate
            uv pip install pytest coverage parameterized
            coverage run --source tap_harvest -m pytest tests/unittests
      - run:
          name: 'Coverage Report'
          command: |
            source /usr/local/share/virtualenvs/tap-harvest/bin/activate
            coverage report -m --fail-under=100
            coverage html
      - store_test_results:
          path: test_output/report.xml
      - store_artifacts:
          path: htmlcov
      - add_ssh_keys
      - run:
          name: 'Integration Tests'
          no_output_timeout: 30m
          command: |
            source /usr/local/share/virtualenvs/tap-tester/bin/activate
            uv pip install --upgrade awscli
            aws s3 cp s3://com-stitchdata-dev-deployment-assets/environments/tap-tester/tap_tester_sandbox dev_env.sh
            source dev_env.sh
            unset RP_ENDPOINT
            unset RP_PROJECT
            unset RP_UUID
            unset RP_API_KEY
            unset RP_LAUNCH
            unset RP_LAUNCH_NAME
            unset RP_DESCRIPTION
            unset RP_ATTRIBUTES
            unset REPORT_PORTAL_ENDPOINT
            unset REPORT_PORTAL_PROJECT
            unset REPORT_PORTAL_UUID
            unset REPORT_PORTAL_API_KEY
            export RP_ENABLED=false
            export REPORT_PORTAL_ENABLED=false
            unset USE_STITCH_BACKEND
            run-test --tap=tap-harvest tests

workflows:
  version: 2
  commit:
    jobs:
      - build:
          context: circleci-user
  build_daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: circleci-user
